<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $properties = [
            [
                'id' => 1,
                'title' => 'Appartement 3 chambres Cocody',
                'description' => 'Appartement moderne 3 chambres, meublé, climatisé',
                'catalog_type' => 'residential',
                'property_type' => 'apartment',
                'operation_type' => 'rent',
                'price' => 250000.00,
                'currency' => 'XOF',
                'price_period' => 'monthly',
                'condition' => 'good',
                'address' => 'Cocody, Riviera 3',
                'city' => 'Abidjan',
                'region' => 'Lagunes',
                'neighborhood' => 'Riviera 3',
                'latitude' => 5.3600,
                'longitude' => -3.9700,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'surface_area' => 120.00,
                'floors' => 1,
                'star_rating' => 5,
                'photos' => json_encode([["photo_url" => "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800", "is_main" => true], ["photo_url" => "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800", "is_main" => false]]),
                'amenities' => json_encode(['pool', 'gym', 'parking', 'security']),
                'owner_id' => 3,
                'owner_name' => 'Marie Martin',
                'owner_phone' => '+2250700000003',
                'agent_id' => 2,
                'agent_name' => 'Jean Dupont',
                'is_available' => false,
                'is_featured' => true,
                'is_occupied' => true,
                'occupied_by_user_id' => 4,
                'occupied_by_user_name' => 'Paul Durand',
                'occupied_at' => now()->subDays(1),
                'status' => 'validated',
                'was_auto_validated' => false,
            ],
            [
                'id' => 2,
                'title' => 'Villa 4 chambres Marcory',
                'description' => 'Grande villa familiale avec jardin',
                'catalog_type' => 'residential',
                'property_type' => 'villa',
                'operation_type' => 'sale',
                'price' => 75000000.00,
                'currency' => 'XOF',
                'price_period' => 'once',
                'condition' => 'good',
                'address' => 'Marcory Zone 4',
                'city' => 'Abidjan',
                'region' => 'Lagunes',
                'neighborhood' => 'Zone 4',
                'latitude' => 5.3000,
                'longitude' => -4.0000,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'surface_area' => 300.00,
                'floors' => 2,
                'star_rating' => 4,
                'photos' => json_encode([["photo_url" => "https://images.unsplash.com/photo-1583608205776-b5af1c9b9a3f?w=800", "is_main" => true]]),
                'amenities' => json_encode(['garden', 'garage', 'air_conditioning']),
                'owner_id' => 3,
                'owner_name' => 'Marie Martin',
                'owner_phone' => '+2250700000003',
                'agent_id' => 2,
                'agent_name' => 'Jean Dupont',
                'is_available' => true,
                'is_featured' => false,
                'is_occupied' => false,
                'status' => 'pending',
                'was_auto_validated' => false,
            ],
            [
                'id' => 3,
                'title' => 'Studio Treichville',
                'description' => 'Studio meublé pour célibataire',
                'catalog_type' => 'residential',
                'property_type' => 'studio',
                'operation_type' => 'rent',
                'price' => 85000.00,
                'currency' => 'XOF',
                'price_period' => 'monthly',
                'condition' => 'average',
                'address' => 'Treichville Cité Rouge',
                'city' => 'Abidjan',
                'region' => 'Lagunes',
                'neighborhood' => 'Cité Rouge',
                'latitude' => 5.2900,
                'longitude' => -4.0200,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'surface_area' => 35.00,
                'floors' => 1,
                'star_rating' => 3,
                'photos' => json_encode([["photo_url" => "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800", "is_main" => true]]),
                'amenities' => json_encode(['wifi', 'kitchen']),
                'owner_id' => 3,
                'owner_name' => 'Marie Martin',
                'owner_phone' => '+2250700000003',
                'agent_id' => null,
                'agent_name' => null,
                'is_available' => true,
                'is_featured' => false,
                'is_occupied' => false,
                'status' => 'rejected',
                'was_auto_validated' => false,
                'rejection_reason' => 'Photos insuffisantes',
            ],
            [
                'id' => 4,
                'title' => 'Bureau Zone 4',
                'description' => 'Bureau professionnel climatisé',
                'catalog_type' => 'commercial',
                'property_type' => 'bureau',
                'operation_type' => 'rent',
                'price' => 500000.00,
                'currency' => 'XOF',
                'price_period' => 'monthly',
                'condition' => 'good',
                'address' => 'Zone 4 Immeuble Ariane',
                'city' => 'Abidjan',
                'region' => 'Lagunes',
                'neighborhood' => 'Zone 4',
                'latitude' => 5.3100,
                'longitude' => -4.0100,
                'bedrooms' => 0,
                'bathrooms' => 2,
                'surface_area' => 80.00,
                'floors' => 5,
                'star_rating' => 5,
                'photos' => json_encode([["photo_url" => "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800", "is_main" => true]]),
                'amenities' => json_encode(['elevator', 'parking', 'security']),
                'owner_id' => 3,
                'owner_name' => 'Marie Martin',
                'owner_phone' => '+2250700000003',
                'agent_id' => 2,
                'agent_name' => 'Jean Dupont',
                'is_available' => true,
                'is_featured' => true,
                'is_occupied' => false,
                'status' => 'validated',
                'was_auto_validated' => false,
            ],
            [
                'id' => 5,
                'title' => 'Terrain constructible Bingerville',
                'description' => 'Terrain de 500m² viabilisé',
                'catalog_type' => 'project',
                'property_type' => 'land',
                'operation_type' => 'sale',
                'price' => 15000000.00,
                'currency' => 'XOF',
                'price_period' => 'once',
                'condition' => 'new',
                'address' => 'Bingerville PK24',
                'city' => 'Bingerville',
                'region' => 'Lagunes',
                'neighborhood' => 'PK24',
                'latitude' => 5.3500,
                'longitude' => -3.8900,
                'bedrooms' => 0,
                'bathrooms' => 0,
                'surface_area' => 500.00,
                'floors' => 0,
                'star_rating' => 1,
                'photos' => json_encode([["photo_url" => "https://images.unsplash.com/photo-1536623488768-fb7a95d3e414?w=800", "is_main" => true]]),
                'amenities' => json_encode(['water', 'electricity']),
                'owner_id' => 3,
                'owner_name' => 'Marie Martin',
                'owner_phone' => '+2250700000003',
                'agent_id' => null,
                'agent_name' => null,
                'is_available' => true,
                'is_featured' => false,
                'is_occupied' => false,
                'status' => 'pending',
                'was_auto_validated' => false,
            ],
        ];

        foreach ($properties as $property) {
            $data = $property;
            $data['created_at'] = now();
            $data['updated_at'] = now();
            DB::table('properties')->updateOrInsert(['id' => $property['id']], $data);
        }

        echo "✅ 5 propriétés créées (IDs 1-5) pour toutes sections\n";
    }
}

